site_name: Max1122Chen's Blog
site_author: Max1122Chen

repo_name: Max1122Chen.github.io
repo_url: https://github.com/Max1122Chen/Max1122Chen.github.io

theme:
  name: material
  language: zh
  static_templates:
    - 404.html

  features:
    - header.autohide
    - navigation.instant
    - search.hightlight

  palette:
    primary: red
    accent: indigo

markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences


plugins:
  - search
  - awesome-nav

extra:
  generator: false

watch: 
  - ./