site_name: Max1122Chen
site_description: 游戏开发 · 计算机图形学 · 个人主页与学习笔记
site_author: Max1122Chen
site_url: https://max1122chen.github.io

repo_name: Max1122Chen.github.io
repo_url: https://github.com/Max1122Chen/Max1122Chen.github.io

theme:
  name: material
  language: zh
  static_templates:
    - 404.html

  features:
    - header.autohide
    - navigation.instant
    - search.highlight
    - navigation.tabs
    - navigation.top
    - content.code.copy

  palette:
    primary: deep-purple
    accent: indigo

markdown_extensions:
  - meta
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - awesome-nav

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Max1122Chen

watch: 
  - ./